version: "3.8"

services:
  adonis:
    container_name: adonis
    image: adonis:1.0
    ports:
      - 8010:8010
    networks:
      - adonis-network

  nginx:
    container_name: nginx
    image: nginx:1.17.2
    ports:
      - 80:80
    networks:
      - adonis-network
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - adonis

networks:
  adonis-network:
    name: adonis-network
